---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kafka
  name: kafka-01
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-01
      labels:
        app: kafka-01
    spec:
      hostname: kafka-01
      containers:
      - name: kafka-01
        image: confluentinc/cp-kafka:3.3.0-1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-01:2181"
          - name: KAFKA_BROKER_ID
            value: "101"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_OPTS
            value: "-Djava.net.preferIPv4Stack=true"
          - name: KAFKA_METRICS_REPORTERS
            value: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
          - name: KAFKA_CONFLUENT_METRICS_REPORT_BOOTSTRAP_SERVERS
            value: "kafka-01:9092"
          - name: KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
            value: "1"
        volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: kafka-01-data
      volumes:
        - name: kafka-01-data
          emptyDir: {}
